# raw 타입의 데이터를 http url 로부터 불러와 pvc 에 import 한 dv 를 생성하는 예입니다.
# This example assumes you are using a default storage class
apiVersion: cdi.kubevirt.io/v1alpha1
kind: DataVolume
metadata:
  name: my-data-volume
spec:
  source:
      http:
         url: "https://download.cirros-cloud.net/0.4.0/cirros-0.4.0-x86_64-disk.img"
  pvc:
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 1Gi
