apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: ceph-file-sc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cephfs-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cephfs-nginx
  template:
    metadata:
      labels:
        app: cephfs-nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: cephfs
          mountPath: /mnt/cephfs
      volumes:
      - name: cephfs
        persistentVolumeClaim:
          claimName: cephfs-pvc
          readOnly: false
